/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetTenantRequest = {
  /**
   * Tenant ID
   */
  id: string;
};

export type GetTenantResponse =
  | shared.DtoTenantResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type GetTenantRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetTenantRequest$outboundSchema: z.ZodType<
  GetTenantRequest$Outbound,
  z.ZodTypeDef,
  GetTenantRequest
> = z.object({
  id: z.string(),
});

export function getTenantRequestToJSON(
  getTenantRequest: GetTenantRequest,
): string {
  return JSON.stringify(
    GetTenantRequest$outboundSchema.parse(getTenantRequest),
  );
}

/** @internal */
export const GetTenantResponse$inboundSchema: z.ZodType<
  GetTenantResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoTenantResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function getTenantResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTenantResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTenantResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTenantResponse' from JSON`,
  );
}
