/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { alertsQueryAlertLog } from "../funcs/alerts-query-alert-log.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Alerts extends ClientSDK {
  /**
   * Query alert logs
   *
   * @remarks
   * Use when viewing or searching alert history (e.g. support triage or customer-facing alert log). Returns a paginated list; supports filtering by type, customer, subscription.
   */
  async queryAlertLog(
    request: models.TypesAlertLogFilter,
    options?: RequestOptions,
  ): Promise<models.DtoListAlertLogsResponse> {
    return unwrapAsync(alertsQueryAlertLog(
      this,
      request,
      options,
    ));
  }
}
