/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { couponsCreateCoupon } from "../funcs/coupons-create-coupon.js";
import { couponsDeleteCoupon } from "../funcs/coupons-delete-coupon.js";
import { couponsGetCoupon } from "../funcs/coupons-get-coupon.js";
import { couponsQueryCoupon } from "../funcs/coupons-query-coupon.js";
import { couponsUpdateCoupon } from "../funcs/coupons-update-coupon.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Coupons extends ClientSDK {
  /**
   * Create coupon
   *
   * @remarks
   * Use when creating a discount (e.g. promo code or referral). Ideal for percent or fixed value, with optional validity and usage limits.
   */
  async createCoupon(
    request: models.DtoCreateCouponRequest,
    options?: RequestOptions,
  ): Promise<models.DtoCouponResponse> {
    return unwrapAsync(couponsCreateCoupon(
      this,
      request,
      options,
    ));
  }

  /**
   * Query coupons
   *
   * @remarks
   * Use when listing or searching coupons (e.g. promo management). Returns a paginated list; supports filtering and sorting.
   */
  async queryCoupon(
    request: models.TypesCouponFilter,
    options?: RequestOptions,
  ): Promise<models.DtoListCouponsResponse> {
    return unwrapAsync(couponsQueryCoupon(
      this,
      request,
      options,
    ));
  }

  /**
   * Get coupon
   *
   * @remarks
   * Use when you need to load a single coupon (e.g. for display or to validate a code).
   */
  async getCoupon(
    request: operations.GetCouponRequest,
    options?: RequestOptions,
  ): Promise<models.DtoCouponResponse> {
    return unwrapAsync(couponsGetCoupon(
      this,
      request,
      options,
    ));
  }

  /**
   * Update coupon
   *
   * @remarks
   * Use when changing coupon config (e.g. value, validity, or usage limits).
   */
  async updateCoupon(
    request: operations.UpdateCouponRequest,
    options?: RequestOptions,
  ): Promise<models.DtoCouponResponse> {
    return unwrapAsync(couponsUpdateCoupon(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete coupon
   *
   * @remarks
   * Use when retiring a coupon (e.g. campaign ended). Returns 200 with success message.
   */
  async deleteCoupon(
    request: operations.DeleteCouponRequest,
    options?: RequestOptions,
  ): Promise<{ [k: string]: string }> {
    return unwrapAsync(couponsDeleteCoupon(
      this,
      request,
      options,
    ));
  }
}
