/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { environmentsCreateEnvironment } from "../funcs/environments-create-environment.js";
import { environmentsUpdateEnvironment } from "../funcs/environments-update-environment.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Environments extends ClientSDK {
  /**
   * Create environment
   *
   * @remarks
   * Use when setting up a new environment (e.g. production, staging) for the tenant. Ideal for separating billing or config per environment.
   */
  async createEnvironment(
    request: models.DtoCreateEnvironmentRequest,
    options?: RequestOptions,
  ): Promise<models.DtoEnvironmentResponse> {
    return unwrapAsync(environmentsCreateEnvironment(
      this,
      request,
      options,
    ));
  }

  /**
   * Update environment
   *
   * @remarks
   * Use when changing environment name or settings (e.g. renaming or updating metadata).
   */
  async updateEnvironment(
    request: operations.UpdateEnvironmentRequest,
    options?: RequestOptions,
  ): Promise<models.DtoEnvironmentResponse> {
    return unwrapAsync(environmentsUpdateEnvironment(
      this,
      request,
      options,
    ));
  }
}
