/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupsCreateGroup } from "../funcs/groups-create-group.js";
import { groupsDeleteGroup } from "../funcs/groups-delete-group.js";
import { groupsGetGroup } from "../funcs/groups-get-group.js";
import { groupsQueryGroup } from "../funcs/groups-query-group.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Groups extends ClientSDK {
  /**
   * Create group
   *
   * @remarks
   * Use when organizing entities into a group (e.g. for filtering prices or plans by product line or region).
   */
  async createGroup(
    request: models.DtoCreateGroupRequest,
    options?: RequestOptions,
  ): Promise<models.DtoGroupResponse> {
    return unwrapAsync(groupsCreateGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Query groups
   *
   * @remarks
   * Use when listing or searching groups (e.g. admin catalog). Returns a paginated list; supports filtering and sorting.
   */
  async queryGroup(
    request: models.TypesGroupFilter,
    options?: RequestOptions,
  ): Promise<models.DtoListGroupsResponse> {
    return unwrapAsync(groupsQueryGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Get group
   *
   * @remarks
   * Use when you need to load a single group (e.g. for display or to assign entities).
   */
  async getGroup(
    request: operations.GetGroupRequest,
    options?: RequestOptions,
  ): Promise<models.DtoGroupResponse> {
    return unwrapAsync(groupsGetGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete group
   *
   * @remarks
   * Use when removing a group and clearing its entity associations (e.g. retiring a product line). Returns 204 or 200 on success.
   */
  async deleteGroup(
    request: operations.DeleteGroupRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(groupsDeleteGroup(
      this,
      request,
      options,
    ));
  }
}
