/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsCreateOrUpdateIntegration } from "../funcs/integrations-create-or-update-integration.js";
import { integrationsDeleteIntegration } from "../funcs/integrations-delete-integration.js";
import { integrationsGetIntegration } from "../funcs/integrations-get-integration.js";
import { integrationsListLinkedIntegrations } from "../funcs/integrations-list-linked-integrations.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Integrations extends ClientSDK {
  /**
   * Get integration details
   *
   * @remarks
   * Use when you need to check or display integration config (e.g. which provider is linked). Sensitive values may be redacted.
   */
  async getIntegration(
    request: operations.GetIntegrationRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSecretResponse> {
    return unwrapAsync(integrationsGetIntegration(
      this,
      request,
      options,
    ));
  }

  /**
   * Create or update an integration
   *
   * @remarks
   * Use when storing or updating credentials for an external integration (e.g. Stripe, HubSpot). Secrets are encrypted at rest.
   */
  async createOrUpdateIntegration(
    request: operations.CreateOrUpdateIntegrationRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSecretResponse> {
    return unwrapAsync(integrationsCreateOrUpdateIntegration(
      this,
      request,
      options,
    ));
  }

  /**
   * List linked integrations
   *
   * @remarks
   * Use when showing which integrations are connected (e.g. settings page). Returns providers that have valid linked credentials.
   */
  async listLinkedIntegrations(
    options?: RequestOptions,
  ): Promise<models.DtoLinkedIntegrationsResponse> {
    return unwrapAsync(integrationsListLinkedIntegrations(
      this,
      options,
    ));
  }

  /**
   * Delete an integration
   *
   * @remarks
   * Use when disconnecting an integration (e.g. switching provider or removing OAuth). Deletes stored credentials.
   */
  async deleteIntegration(
    request: operations.DeleteIntegrationRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(integrationsDeleteIntegration(
      this,
      request,
      options,
    ));
  }
}
