/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesAttemptInvoicePayment } from "../funcs/invoices-attempt-invoice-payment.js";
import { invoicesCreateInvoice } from "../funcs/invoices-create-invoice.js";
import { invoicesFinalizeInvoice } from "../funcs/invoices-finalize-invoice.js";
import { invoicesGetCustomerInvoiceSummary } from "../funcs/invoices-get-customer-invoice-summary.js";
import { invoicesGetInvoicePdf } from "../funcs/invoices-get-invoice-pdf.js";
import { invoicesGetInvoicePreview } from "../funcs/invoices-get-invoice-preview.js";
import { invoicesGetInvoice } from "../funcs/invoices-get-invoice.js";
import { invoicesQueryInvoice } from "../funcs/invoices-query-invoice.js";
import { invoicesRecalculateInvoice } from "../funcs/invoices-recalculate-invoice.js";
import { invoicesTriggerInvoiceCommsWebhook } from "../funcs/invoices-trigger-invoice-comms-webhook.js";
import { invoicesUpdateInvoicePaymentStatus } from "../funcs/invoices-update-invoice-payment-status.js";
import { invoicesUpdateInvoice } from "../funcs/invoices-update-invoice.js";
import { invoicesVoidInvoice } from "../funcs/invoices-void-invoice.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Invoices extends ClientSDK {
  /**
   * Get customer invoice summary
   *
   * @remarks
   * Use when showing a customer's invoice overview (e.g. billing portal or balance summary). Includes totals and multi-currency breakdown.
   */
  async getCustomerInvoiceSummary(
    request: operations.GetCustomerInvoiceSummaryRequest,
    options?: RequestOptions,
  ): Promise<models.DtoCustomerMultiCurrencyInvoiceSummary> {
    return unwrapAsync(invoicesGetCustomerInvoiceSummary(
      this,
      request,
      options,
    ));
  }

  /**
   * Create one-off invoice
   *
   * @remarks
   * Use when creating a manual or one-off invoice (e.g. custom charge or non-recurring billing). Invoice is created in draft; finalize when ready.
   */
  async createInvoice(
    request: models.DtoCreateInvoiceRequest,
    options?: RequestOptions,
  ): Promise<models.DtoInvoiceResponse> {
    return unwrapAsync(invoicesCreateInvoice(
      this,
      request,
      options,
    ));
  }

  /**
   * Get invoice preview
   *
   * @remarks
   * Use when showing a customer what they will be charged (e.g. preview before checkout or plan change). No invoice is created.
   */
  async getInvoicePreview(
    request: models.DtoGetPreviewInvoiceRequest,
    options?: RequestOptions,
  ): Promise<models.DtoInvoiceResponse> {
    return unwrapAsync(invoicesGetInvoicePreview(
      this,
      request,
      options,
    ));
  }

  /**
   * Query invoices
   *
   * @remarks
   * Use when listing or searching invoices (e.g. admin view or customer history). Returns a paginated list; supports filtering by customer, status, date range.
   */
  async queryInvoice(
    request: models.TypesInvoiceFilter,
    options?: RequestOptions,
  ): Promise<models.DtoListInvoicesResponse> {
    return unwrapAsync(invoicesQueryInvoice(
      this,
      request,
      options,
    ));
  }

  /**
   * Get invoice
   *
   * @remarks
   * Use when loading an invoice for display or editing (e.g. portal or reconciliation). Supports group_by for usage breakdown and force_runtime_recalculation.
   */
  async getInvoice(
    request: operations.GetInvoiceRequest,
    options?: RequestOptions,
  ): Promise<models.DtoInvoiceResponse> {
    return unwrapAsync(invoicesGetInvoice(
      this,
      request,
      options,
    ));
  }

  /**
   * Update invoice
   *
   * @remarks
   * Use when updating invoice metadata or due date (e.g. PDF URL, net terms). For paid invoices only safe fields can be updated.
   */
  async updateInvoice(
    request: operations.UpdateInvoiceRequest,
    options?: RequestOptions,
  ): Promise<models.DtoInvoiceResponse> {
    return unwrapAsync(invoicesUpdateInvoice(
      this,
      request,
      options,
    ));
  }

  /**
   * Trigger invoice communication webhook
   *
   * @remarks
   * Use when sending an invoice to the customer (e.g. trigger email or Slack). Payload includes full invoice details for your integration.
   */
  async triggerInvoiceCommsWebhook(
    request: operations.TriggerInvoiceCommsWebhookRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSuccessResponse> {
    return unwrapAsync(invoicesTriggerInvoiceCommsWebhook(
      this,
      request,
      options,
    ));
  }

  /**
   * Finalize invoice
   *
   * @remarks
   * Use when locking an invoice for payment (e.g. after review). Once finalized, line items are locked; invoice can be paid or voided.
   */
  async finalizeInvoice(
    request: operations.FinalizeInvoiceRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSuccessResponse> {
    return unwrapAsync(invoicesFinalizeInvoice(
      this,
      request,
      options,
    ));
  }

  /**
   * Update invoice payment status
   *
   * @remarks
   * Use when reconciling payment status from an external gateway or manual entry (e.g. mark paid after bank confirmation).
   */
  async updateInvoicePaymentStatus(
    request: operations.UpdateInvoicePaymentStatusRequest,
    options?: RequestOptions,
  ): Promise<models.DtoInvoiceResponse> {
    return unwrapAsync(invoicesUpdateInvoicePaymentStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Attempt invoice payment
   *
   * @remarks
   * Use when paying an invoice with the customer's wallet balance (e.g. prepaid credits or balance applied at checkout).
   */
  async attemptInvoicePayment(
    request: operations.AttemptInvoicePaymentRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSuccessResponse> {
    return unwrapAsync(invoicesAttemptInvoicePayment(
      this,
      request,
      options,
    ));
  }

  /**
   * Get invoice PDF
   *
   * @remarks
   * Use when delivering an invoice PDF to the customer (e.g. email attachment or download). Use url=true for a presigned URL instead of binary.
   */
  async getInvoicePdf(
    request: operations.GetInvoicePdfRequest,
    options?: RequestOptions,
  ): Promise<ReadableStream<Uint8Array>> {
    return unwrapAsync(invoicesGetInvoicePdf(
      this,
      request,
      options,
    ));
  }

  /**
   * Recalculate invoice
   *
   * @remarks
   * Use when subscription or usage data changed and you need to refresh a draft invoice before finalizing. Optional finalize=true to lock after recalc.
   */
  async recalculateInvoice(
    request: operations.RecalculateInvoiceRequest,
    options?: RequestOptions,
  ): Promise<models.DtoInvoiceResponse> {
    return unwrapAsync(invoicesRecalculateInvoice(
      this,
      request,
      options,
    ));
  }

  /**
   * Void invoice
   *
   * @remarks
   * Use when cancelling an invoice (e.g. order cancelled or duplicate). Only unpaid invoices can be voided.
   */
  async voidInvoice(
    request: operations.VoidInvoiceRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSuccessResponse> {
    return unwrapAsync(invoicesVoidInvoice(
      this,
      request,
      options,
    ));
  }
}
