/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { priceUnitsCreatePriceUnit } from "../funcs/price-units-create-price-unit.js";
import { priceUnitsDeletePriceUnit } from "../funcs/price-units-delete-price-unit.js";
import { priceUnitsGetPriceUnitByCode } from "../funcs/price-units-get-price-unit-by-code.js";
import { priceUnitsGetPriceUnit } from "../funcs/price-units-get-price-unit.js";
import { priceUnitsListPriceUnits } from "../funcs/price-units-list-price-units.js";
import { priceUnitsQueryPriceUnit } from "../funcs/price-units-query-price-unit.js";
import { priceUnitsUpdatePriceUnit } from "../funcs/price-units-update-price-unit.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PriceUnits extends ClientSDK {
  /**
   * List price units
   *
   * @remarks
   * Use when listing price units (e.g. in a catalog or when creating prices). Returns a paginated list; supports status, sort, and pagination.
   */
  async listPriceUnits(
    request?: operations.ListPriceUnitsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.DtoListPriceUnitsResponse> {
    return unwrapAsync(priceUnitsListPriceUnits(
      this,
      request,
      options,
    ));
  }

  /**
   * Create price unit
   *
   * @remarks
   * Use when defining a new unit of measure for pricing (e.g. GB, API call, seat). Ideal for metered or usage-based prices.
   */
  async createPriceUnit(
    request: models.DtoCreatePriceUnitRequest,
    options?: RequestOptions,
  ): Promise<models.DtoCreatePriceUnitResponse> {
    return unwrapAsync(priceUnitsCreatePriceUnit(
      this,
      request,
      options,
    ));
  }

  /**
   * Get price unit by code
   *
   * @remarks
   * Use when resolving a price unit by code (e.g. from an external catalog or config). Ideal for integrations.
   */
  async getPriceUnitByCode(
    request: operations.GetPriceUnitByCodeRequest,
    options?: RequestOptions,
  ): Promise<models.DtoPriceUnitResponse> {
    return unwrapAsync(priceUnitsGetPriceUnitByCode(
      this,
      request,
      options,
    ));
  }

  /**
   * Query price units
   *
   * @remarks
   * Use when searching or listing price units (e.g. admin catalog). Returns a paginated list; supports filtering and sorting.
   */
  async queryPriceUnit(
    request: models.TypesPriceUnitFilter,
    options?: RequestOptions,
  ): Promise<models.DtoListPriceUnitsResponse> {
    return unwrapAsync(priceUnitsQueryPriceUnit(
      this,
      request,
      options,
    ));
  }

  /**
   * Get price unit
   *
   * @remarks
   * Use when you need to load a single price unit (e.g. for display or when creating a price).
   */
  async getPriceUnit(
    request: operations.GetPriceUnitRequest,
    options?: RequestOptions,
  ): Promise<models.DtoPriceUnitResponse> {
    return unwrapAsync(priceUnitsGetPriceUnit(
      this,
      request,
      options,
    ));
  }

  /**
   * Update price unit
   *
   * @remarks
   * Use when renaming or updating metadata for a price unit. Code is immutable once created.
   */
  async updatePriceUnit(
    request: operations.UpdatePriceUnitRequest,
    options?: RequestOptions,
  ): Promise<models.DtoPriceUnitResponse> {
    return unwrapAsync(priceUnitsUpdatePriceUnit(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete price unit
   *
   * @remarks
   * Use when removing a price unit that is no longer needed. Fails if any price references this unit.
   */
  async deletePriceUnit(
    request: operations.DeletePriceUnitRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSuccessResponse> {
    return unwrapAsync(priceUnitsDeletePriceUnit(
      this,
      request,
      options,
    ));
  }
}
