/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { secretsCreateApiKey } from "../funcs/secrets-create-api-key.js";
import { secretsDeleteApiKey } from "../funcs/secrets-delete-api-key.js";
import { secretsListApiKeys } from "../funcs/secrets-list-api-keys.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Secrets extends ClientSDK {
  /**
   * List API keys
   *
   * @remarks
   * Use when listing API keys (e.g. admin view or rotating keys). Returns a paginated list.
   */
  async listApiKeys(
    request?: operations.ListApiKeysRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.DtoListSecretsResponse> {
    return unwrapAsync(secretsListApiKeys(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new API key
   *
   * @remarks
   * Use when issuing a new API key (e.g. for a service account or for the current user). Provide service_account_id to create for a service account.
   */
  async createApiKey(
    request: models.DtoCreateAPIKeyRequest,
    options?: RequestOptions,
  ): Promise<models.DtoCreateAPIKeyResponse> {
    return unwrapAsync(secretsCreateApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an API key
   *
   * @remarks
   * Use when revoking an API key (e.g. rotation or compromise). Permanently invalidates the key.
   */
  async deleteApiKey(
    request: operations.DeleteApiKeyRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(secretsDeleteApiKey(
      this,
      request,
      options,
    ));
  }
}
