/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsActivateSubscription } from "../funcs/subscriptions-activate-subscription.js";
import { subscriptionsAddSubscriptionAddon } from "../funcs/subscriptions-add-subscription-addon.js";
import { subscriptionsCancelSubscriptionSchedule } from "../funcs/subscriptions-cancel-subscription-schedule.js";
import { subscriptionsCancelSubscription } from "../funcs/subscriptions-cancel-subscription.js";
import { subscriptionsCreateSubscriptionLineItem } from "../funcs/subscriptions-create-subscription-line-item.js";
import { subscriptionsCreateSubscription } from "../funcs/subscriptions-create-subscription.js";
import { subscriptionsDeleteSubscriptionLineItem } from "../funcs/subscriptions-delete-subscription-line-item.js";
import { subscriptionsExecuteSubscriptionChange } from "../funcs/subscriptions-execute-subscription-change.js";
import { subscriptionsGetSubscriptionAddonAssociations } from "../funcs/subscriptions-get-subscription-addon-associations.js";
import { subscriptionsGetSubscriptionEntitlements } from "../funcs/subscriptions-get-subscription-entitlements.js";
import { subscriptionsGetSubscriptionSchedule } from "../funcs/subscriptions-get-subscription-schedule.js";
import { subscriptionsGetSubscriptionUpcomingGrants } from "../funcs/subscriptions-get-subscription-upcoming-grants.js";
import { subscriptionsGetSubscriptionUsage } from "../funcs/subscriptions-get-subscription-usage.js";
import { subscriptionsGetSubscriptionV2 } from "../funcs/subscriptions-get-subscription-v2.js";
import { subscriptionsGetSubscription } from "../funcs/subscriptions-get-subscription.js";
import { subscriptionsListAllSubscriptionSchedules } from "../funcs/subscriptions-list-all-subscription-schedules.js";
import { subscriptionsListSubscriptionPauses } from "../funcs/subscriptions-list-subscription-pauses.js";
import { subscriptionsListSubscriptionSchedules } from "../funcs/subscriptions-list-subscription-schedules.js";
import { subscriptionsPauseSubscription } from "../funcs/subscriptions-pause-subscription.js";
import { subscriptionsPreviewSubscriptionChange } from "../funcs/subscriptions-preview-subscription-change.js";
import { subscriptionsQuerySubscription } from "../funcs/subscriptions-query-subscription.js";
import { subscriptionsRemoveSubscriptionAddon } from "../funcs/subscriptions-remove-subscription-addon.js";
import { subscriptionsResumeSubscription } from "../funcs/subscriptions-resume-subscription.js";
import { subscriptionsUpdateSubscriptionLineItem } from "../funcs/subscriptions-update-subscription-line-item.js";
import { subscriptionsUpdateSubscription } from "../funcs/subscriptions-update-subscription.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Subscriptions extends ClientSDK {
  /**
   * Create subscription
   *
   * @remarks
   * Use when onboarding a customer to a plan or starting a new subscription. Ideal for draft subscriptions (activate later) or active from start.
   */
  async createSubscription(
    request: models.DtoCreateSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSubscriptionResponse> {
    return unwrapAsync(subscriptionsCreateSubscription(
      this,
      request,
      options,
    ));
  }

  /**
   * Add addon to subscription
   *
   * @remarks
   * Use when adding an optional product or add-on to an existing subscription (e.g. extra storage or support tier).
   */
  async addSubscriptionAddon(
    request: models.DtoAddAddonRequest,
    options?: RequestOptions,
  ): Promise<models.DtoAddonAssociationResponse> {
    return unwrapAsync(subscriptionsAddSubscriptionAddon(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove addon from subscription
   *
   * @remarks
   * Use when removing an add-on from a subscription (e.g. downgrade or opt-out).
   */
  async removeSubscriptionAddon(
    request: models.DtoRemoveAddonRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSuccessResponse> {
    return unwrapAsync(subscriptionsRemoveSubscriptionAddon(
      this,
      request,
      options,
    ));
  }

  /**
   * Update subscription line item
   *
   * @remarks
   * Use when changing a subscription line item (e.g. quantity or price). Implemented by ending the current line and creating a new one for clean billing.
   */
  async updateSubscriptionLineItem(
    request: operations.UpdateSubscriptionLineItemRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSubscriptionLineItemResponse> {
    return unwrapAsync(subscriptionsUpdateSubscriptionLineItem(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete subscription line item
   *
   * @remarks
   * Use when removing a charge or seat from a subscription (e.g. downgrade). Line item ends; retained for history but no longer billed.
   */
  async deleteSubscriptionLineItem(
    request: operations.DeleteSubscriptionLineItemRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSubscriptionLineItemResponse> {
    return unwrapAsync(subscriptionsDeleteSubscriptionLineItem(
      this,
      request,
      options,
    ));
  }

  /**
   * Query subscriptions
   *
   * @remarks
   * Use when listing or searching subscriptions (e.g. admin view or customer subscription list). Returns a paginated list; supports filtering by customer, plan, status.
   */
  async querySubscription(
    request: models.TypesSubscriptionFilter,
    options?: RequestOptions,
  ): Promise<models.DtoListSubscriptionsResponse> {
    return unwrapAsync(subscriptionsQuerySubscription(
      this,
      request,
      options,
    ));
  }

  /**
   * Get usage by subscription
   *
   * @remarks
   * Use when showing usage for a subscription (e.g. in a portal or for overage checks). Supports time range and filters.
   */
  async getSubscriptionUsage(
    request: models.DtoGetUsageBySubscriptionRequest,
    options?: RequestOptions,
  ): Promise<models.DtoGetUsageBySubscriptionResponse> {
    return unwrapAsync(subscriptionsGetSubscriptionUsage(
      this,
      request,
      options,
    ));
  }

  /**
   * Get subscription
   *
   * @remarks
   * Use when you need to load a single subscription (e.g. for a billing portal or to check status).
   */
  async getSubscription(
    request: operations.GetSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSubscriptionResponse> {
    return unwrapAsync(subscriptionsGetSubscription(
      this,
      request,
      options,
    ));
  }

  /**
   * Update subscription
   *
   * @remarks
   * Use when changing subscription details (e.g. quantity, billing anchor, or parent). Supports partial update; send "" to clear parent_subscription_id.
   */
  async updateSubscription(
    request: operations.UpdateSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSubscriptionResponse> {
    return unwrapAsync(subscriptionsUpdateSubscription(
      this,
      request,
      options,
    ));
  }

  /**
   * Activate draft subscription
   *
   * @remarks
   * Use when turning a draft subscription live (e.g. after collecting payment or completing setup). Once activated, billing and entitlements apply.
   */
  async activateSubscription(
    request: operations.ActivateSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSubscriptionResponse> {
    return unwrapAsync(subscriptionsActivateSubscription(
      this,
      request,
      options,
    ));
  }

  /**
   * Get active addon associations
   *
   * @remarks
   * Use when listing which add-ons are currently attached to a subscription (e.g. for display or editing).
   */
  async getSubscriptionAddonAssociations(
    request: operations.GetSubscriptionAddonAssociationsRequest,
    options?: RequestOptions,
  ): Promise<Array<models.DtoAddonAssociationResponse>> {
    return unwrapAsync(subscriptionsGetSubscriptionAddonAssociations(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel subscription
   *
   * @remarks
   * Use when a customer churns or downgrades. Supports immediate or end-of-period cancellation and proration. Ideal for self-serve or support-driven cancellations.
   */
  async cancelSubscription(
    request: operations.CancelSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<models.DtoCancelSubscriptionResponse> {
    return unwrapAsync(subscriptionsCancelSubscription(
      this,
      request,
      options,
    ));
  }

  /**
   * Execute subscription plan change
   *
   * @remarks
   * Use when applying a plan change (e.g. upgrade or downgrade). Executes proration and generates invoice or credit as needed.
   */
  async executeSubscriptionChange(
    request: operations.ExecuteSubscriptionChangeRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSubscriptionChangeExecuteResponse> {
    return unwrapAsync(subscriptionsExecuteSubscriptionChange(
      this,
      request,
      options,
    ));
  }

  /**
   * Preview subscription plan change
   *
   * @remarks
   * Use when showing a customer the cost of a plan change before they confirm (e.g. upgrade/downgrade preview with proration).
   */
  async previewSubscriptionChange(
    request: operations.PreviewSubscriptionChangeRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSubscriptionChangePreviewResponse> {
    return unwrapAsync(subscriptionsPreviewSubscriptionChange(
      this,
      request,
      options,
    ));
  }

  /**
   * Get subscription entitlements
   *
   * @remarks
   * Use when checking what features or limits a subscription has (e.g. entitlement checks or feature gating). Optional feature_ids to filter.
   */
  async getSubscriptionEntitlements(
    request: operations.GetSubscriptionEntitlementsRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSubscriptionEntitlementsResponse> {
    return unwrapAsync(subscriptionsGetSubscriptionEntitlements(
      this,
      request,
      options,
    ));
  }

  /**
   * Get upcoming credit grant applications
   *
   * @remarks
   * Use when showing upcoming or pending credits for a subscription (e.g. in a portal or for forecasting).
   */
  async getSubscriptionUpcomingGrants(
    request: operations.GetSubscriptionUpcomingGrantsRequest,
    options?: RequestOptions,
  ): Promise<models.DtoListCreditGrantApplicationsResponse> {
    return unwrapAsync(subscriptionsGetSubscriptionUpcomingGrants(
      this,
      request,
      options,
    ));
  }

  /**
   * Create subscription line item
   *
   * @remarks
   * Use when adding a new charge or seat to a subscription (e.g. extra seat or one-time add). Supports price_id or inline price.
   */
  async createSubscriptionLineItem(
    request: operations.CreateSubscriptionLineItemRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSubscriptionLineItemResponse> {
    return unwrapAsync(subscriptionsCreateSubscriptionLineItem(
      this,
      request,
      options,
    ));
  }

  /**
   * Pause a subscription
   *
   * @remarks
   * Use when temporarily stopping a subscription (e.g. customer hold or seasonal pause). Billing and access pause; resume when ready.
   */
  async pauseSubscription(
    request: operations.PauseSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSubscriptionPauseResponse> {
    return unwrapAsync(subscriptionsPauseSubscription(
      this,
      request,
      options,
    ));
  }

  /**
   * List all pauses for a subscription
   *
   * @remarks
   * Use when showing pause history for a subscription (e.g. support or audit). Returns all past and future pauses.
   */
  async listSubscriptionPauses(
    request: operations.ListSubscriptionPausesRequest,
    options?: RequestOptions,
  ): Promise<Array<models.DtoListSubscriptionPausesResponse>> {
    return unwrapAsync(subscriptionsListSubscriptionPauses(
      this,
      request,
      options,
    ));
  }

  /**
   * Resume a paused subscription
   *
   * @remarks
   * Use when reactivating a paused subscription (e.g. end of hold). Billing and access resume from the resume date.
   */
  async resumeSubscription(
    request: operations.ResumeSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSubscriptionPauseResponse> {
    return unwrapAsync(subscriptionsResumeSubscription(
      this,
      request,
      options,
    ));
  }

  /**
   * Get subscription (V2)
   *
   * @remarks
   * Use when you need a subscription with related data (line items, prices, plan). Supports expand for detailed payloads without extra round-trips.
   */
  async getSubscriptionV2(
    request: operations.GetSubscriptionV2Request,
    options?: RequestOptions,
  ): Promise<models.DtoSubscriptionResponseV2> {
    return unwrapAsync(subscriptionsGetSubscriptionV2(
      this,
      request,
      options,
    ));
  }

  /**
   * List all subscription schedules
   *
   * @remarks
   * Use when listing or searching scheduled changes across subscriptions (e.g. admin view). Returns schedules with optional filtering.
   */
  async listAllSubscriptionSchedules(
    request?: operations.ListAllSubscriptionSchedulesRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.DtoGetPendingSchedulesResponse> {
    return unwrapAsync(subscriptionsListAllSubscriptionSchedules(
      this,
      request,
      options,
    ));
  }

  /**
   * Get subscription schedule
   *
   * @remarks
   * Use when you need to load a single scheduled change (e.g. to show when a plan change or renewal takes effect).
   */
  async getSubscriptionSchedule(
    request: operations.GetSubscriptionScheduleRequest,
    options?: RequestOptions,
  ): Promise<models.DtoSubscriptionScheduleResponse> {
    return unwrapAsync(subscriptionsGetSubscriptionSchedule(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel subscription schedule
   *
   * @remarks
   * Use when cancelling a scheduled change (e.g. customer changed mind). Identify by schedule ID in path or by subscription ID + schedule type in body.
   */
  async cancelSubscriptionSchedule(
    request: operations.CancelSubscriptionScheduleRequest,
    options?: RequestOptions,
  ): Promise<models.DtoCancelScheduleResponse> {
    return unwrapAsync(subscriptionsCancelSubscriptionSchedule(
      this,
      request,
      options,
    ));
  }

  /**
   * List subscription schedules
   *
   * @remarks
   * Use when listing scheduled changes for a subscription (e.g. upcoming plan change or renewal). Returns all schedules for that subscription.
   */
  async listSubscriptionSchedules(
    request: operations.ListSubscriptionSchedulesRequest,
    options?: RequestOptions,
  ): Promise<models.DtoGetPendingSchedulesResponse> {
    return unwrapAsync(subscriptionsListSubscriptionSchedules(
      this,
      request,
      options,
    ));
  }
}
