/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxAssociationsCreateTaxAssociation } from "../funcs/tax-associations-create-tax-association.js";
import { taxAssociationsDeleteTaxAssociation } from "../funcs/tax-associations-delete-tax-association.js";
import { taxAssociationsGetTaxAssociation } from "../funcs/tax-associations-get-tax-association.js";
import { taxAssociationsListTaxAssociations } from "../funcs/tax-associations-list-tax-associations.js";
import { taxAssociationsUpdateTaxAssociation } from "../funcs/tax-associations-update-tax-association.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class TaxAssociations extends ClientSDK {
  /**
   * List tax associations
   *
   * @remarks
   * Use when listing tax associations (e.g. tax config or audit). Returns list with optional filtering.
   */
  async listTaxAssociations(
    request?: operations.ListTaxAssociationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.DtoListTaxAssociationsResponse> {
    return unwrapAsync(taxAssociationsListTaxAssociations(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Tax Association
   *
   * @remarks
   * Use when linking a tax rate to an entity (e.g. customer, product, or region) so that rate applies on invoices.
   */
  async createTaxAssociation(
    request: models.DtoCreateTaxAssociationRequest,
    options?: RequestOptions,
  ): Promise<models.DtoTaxAssociationResponse> {
    return unwrapAsync(taxAssociationsCreateTaxAssociation(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Tax Association
   *
   * @remarks
   * Use when you need to load a single tax association (e.g. for display or editing).
   */
  async getTaxAssociation(
    request: operations.GetTaxAssociationRequest,
    options?: RequestOptions,
  ): Promise<models.DtoTaxAssociationResponse> {
    return unwrapAsync(taxAssociationsGetTaxAssociation(
      this,
      request,
      options,
    ));
  }

  /**
   * Update tax association
   *
   * @remarks
   * Use when changing a tax association (e.g. switch rate or entity). Request body contains the fields to update.
   */
  async updateTaxAssociation(
    request: operations.UpdateTaxAssociationRequest,
    options?: RequestOptions,
  ): Promise<models.DtoTaxAssociationResponse> {
    return unwrapAsync(taxAssociationsUpdateTaxAssociation(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete tax association
   *
   * @remarks
   * Use when removing a tax association (e.g. entity no longer subject to that rate).
   */
  async deleteTaxAssociation(
    request: operations.DeleteTaxAssociationRequest,
    options?: RequestOptions,
  ): Promise<models.DtoTaxAssociationResponse> {
    return unwrapAsync(taxAssociationsDeleteTaxAssociation(
      this,
      request,
      options,
    ));
  }
}
