/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tenantsCreateTenant } from "../funcs/tenants-create-tenant.js";
import { tenantsGetTenantBillingUsage } from "../funcs/tenants-get-tenant-billing-usage.js";
import { tenantsGetTenant } from "../funcs/tenants-get-tenant.js";
import { tenantsUpdateTenant } from "../funcs/tenants-update-tenant.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tenants extends ClientSDK {
  /**
   * Get billing usage for the current tenant
   *
   * @remarks
   * Use when showing the current tenant's billing usage (e.g. admin billing page or usage caps). Returns subscription and usage for the tenant.
   */
  async getTenantBillingUsage(
    options?: RequestOptions,
  ): Promise<models.DtoTenantBillingUsage> {
    return unwrapAsync(tenantsGetTenantBillingUsage(
      this,
      options,
    ));
  }

  /**
   * Create a new tenant
   *
   * @remarks
   * Use when provisioning a new tenant (e.g. new org or workspace). Tenants are top-level isolation boundaries.
   */
  async createTenant(
    request: models.DtoCreateTenantRequest,
    options?: RequestOptions,
  ): Promise<models.DtoTenantResponse> {
    return unwrapAsync(tenantsCreateTenant(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a tenant
   *
   * @remarks
   * Use when changing tenant details (e.g. name or billing info). Request body contains the fields to update.
   */
  async updateTenant(
    request: models.DtoUpdateTenantRequest,
    options?: RequestOptions,
  ): Promise<models.DtoTenantResponse> {
    return unwrapAsync(tenantsUpdateTenant(
      this,
      request,
      options,
    ));
  }

  /**
   * Get tenant
   *
   * @remarks
   * Use when you need to load a single tenant (e.g. for display or to check billing). Typically used in admin or multi-tenant contexts.
   */
  async getTenant(
    request: operations.GetTenantRequest,
    options?: RequestOptions,
  ): Promise<models.DtoTenantResponse> {
    return unwrapAsync(tenantsGetTenant(
      this,
      request,
      options,
    ));
  }
}
