/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tenantsCreateTenant } from "../funcs/tenantsCreateTenant.js";
import { tenantsGetTenant } from "../funcs/tenantsGetTenant.js";
import { tenantsGetTenantBillingUsage } from "../funcs/tenantsGetTenantBillingUsage.js";
import { tenantsUpdateTenant } from "../funcs/tenantsUpdateTenant.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Tenants extends ClientSDK {
  /**
   * Create a new tenant
   *
   * @remarks
   * Use when provisioning a new tenant (e.g. new org or workspace). Tenants are top-level isolation boundaries.
   */
  async createTenant(
    request: shared.DtoCreateTenantRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateTenantResponse> {
    return unwrapAsync(tenantsCreateTenant(
      this,
      request,
      options,
    ));
  }

  /**
   * Get tenant
   *
   * @remarks
   * Use when you need to load a single tenant (e.g. for display or to check billing). Typically used in admin or multi-tenant contexts.
   */
  async getTenant(
    request: operations.GetTenantRequest,
    options?: RequestOptions,
  ): Promise<operations.GetTenantResponse> {
    return unwrapAsync(tenantsGetTenant(
      this,
      request,
      options,
    ));
  }

  /**
   * Get billing usage for the current tenant
   *
   * @remarks
   * Use when showing the current tenant's billing usage (e.g. admin billing page or usage caps). Returns subscription and usage for the tenant.
   */
  async getTenantBillingUsage(
    options?: RequestOptions,
  ): Promise<operations.GetTenantBillingUsageResponse> {
    return unwrapAsync(tenantsGetTenantBillingUsage(
      this,
      options,
    ));
  }

  /**
   * Update a tenant
   *
   * @remarks
   * Use when changing tenant details (e.g. name or billing info). Request body contains the fields to update.
   */
  async updateTenant(
    request: shared.DtoUpdateTenantRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateTenantResponse> {
    return unwrapAsync(tenantsUpdateTenant(
      this,
      request,
      options,
    ));
  }
}
