/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the flexprice-ts SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx addonsCreateAddon.example.ts
 */

import { FlexPrice } from "flexprice-ts";

const flexPrice = new FlexPrice({
  serverURL: "https://api.example.com",
  apiKeyAuth: "<YOUR_API_KEY_HERE>",
});

async function main() {
  const result = await flexPrice.addons.createAddon({
    lookupKey: "<value>",
    name: "<value>",
    type: "multiple_instance",
  });

  console.log(result);
}

main().catch(console.error);
