/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CancelSubscriptionScheduleRequest = {
  /**
   * Schedule ID (optional if using request body)
   */
  scheduleId: string;
  /**
   * Cancel request (optional if using path parameter)
   */
  body?: models.DtoCancelScheduleRequest | undefined;
};

/** @internal */
export type CancelSubscriptionScheduleRequest$Outbound = {
  schedule_id: string;
  body?: models.DtoCancelScheduleRequest$Outbound | undefined;
};

/** @internal */
export const CancelSubscriptionScheduleRequest$outboundSchema: z.ZodMiniType<
  CancelSubscriptionScheduleRequest$Outbound,
  CancelSubscriptionScheduleRequest
> = z.pipe(
  z.object({
    scheduleId: z.string(),
    body: z.optional(models.DtoCancelScheduleRequest$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      scheduleId: "schedule_id",
    });
  }),
);

export function cancelSubscriptionScheduleRequestToJSON(
  cancelSubscriptionScheduleRequest: CancelSubscriptionScheduleRequest,
): string {
  return JSON.stringify(
    CancelSubscriptionScheduleRequest$outboundSchema.parse(
      cancelSubscriptionScheduleRequest,
    ),
  );
}
