/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type CancelSubscriptionRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Cancel Subscription Request
   */
  body: models.DtoCancelSubscriptionRequest;
};

/** @internal */
export type CancelSubscriptionRequest$Outbound = {
  id: string;
  body: models.DtoCancelSubscriptionRequest$Outbound;
};

/** @internal */
export const CancelSubscriptionRequest$outboundSchema: z.ZodMiniType<
  CancelSubscriptionRequest$Outbound,
  CancelSubscriptionRequest
> = z.object({
  id: z.string(),
  body: models.DtoCancelSubscriptionRequest$outboundSchema,
});

export function cancelSubscriptionRequestToJSON(
  cancelSubscriptionRequest: CancelSubscriptionRequest,
): string {
  return JSON.stringify(
    CancelSubscriptionRequest$outboundSchema.parse(cancelSubscriptionRequest),
  );
}
