/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type CreateSubscriptionLineItemRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Create Line Item Request
   */
  body: models.DtoCreateSubscriptionLineItemRequest;
};

/** @internal */
export type CreateSubscriptionLineItemRequest$Outbound = {
  id: string;
  body: models.DtoCreateSubscriptionLineItemRequest$Outbound;
};

/** @internal */
export const CreateSubscriptionLineItemRequest$outboundSchema: z.ZodMiniType<
  CreateSubscriptionLineItemRequest$Outbound,
  CreateSubscriptionLineItemRequest
> = z.object({
  id: z.string(),
  body: models.DtoCreateSubscriptionLineItemRequest$outboundSchema,
});

export function createSubscriptionLineItemRequestToJSON(
  createSubscriptionLineItemRequest: CreateSubscriptionLineItemRequest,
): string {
  return JSON.stringify(
    CreateSubscriptionLineItemRequest$outboundSchema.parse(
      createSubscriptionLineItemRequest,
    ),
  );
}
