/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type DeleteSubscriptionLineItemRequest = {
  /**
   * Line Item ID
   */
  id: string;
  /**
   * Delete Line Item Request
   */
  body: models.DtoDeleteSubscriptionLineItemRequest;
};

/** @internal */
export type DeleteSubscriptionLineItemRequest$Outbound = {
  id: string;
  body: models.DtoDeleteSubscriptionLineItemRequest$Outbound;
};

/** @internal */
export const DeleteSubscriptionLineItemRequest$outboundSchema: z.ZodMiniType<
  DeleteSubscriptionLineItemRequest$Outbound,
  DeleteSubscriptionLineItemRequest
> = z.object({
  id: z.string(),
  body: models.DtoDeleteSubscriptionLineItemRequest$outboundSchema,
});

export function deleteSubscriptionLineItemRequestToJSON(
  deleteSubscriptionLineItemRequest: DeleteSubscriptionLineItemRequest,
): string {
  return JSON.stringify(
    DeleteSubscriptionLineItemRequest$outboundSchema.parse(
      deleteSubscriptionLineItemRequest,
    ),
  );
}
