/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type DeleteCreditGrantRequest = {
  /**
   * Credit Grant ID
   */
  id: string;
  /**
   * Optional: effective_date for subscription-scoped grants
   */
  body?: models.DtoDeleteCreditGrantRequest | undefined;
};

/** @internal */
export type DeleteCreditGrantRequest$Outbound = {
  id: string;
  body?: models.DtoDeleteCreditGrantRequest$Outbound | undefined;
};

/** @internal */
export const DeleteCreditGrantRequest$outboundSchema: z.ZodMiniType<
  DeleteCreditGrantRequest$Outbound,
  DeleteCreditGrantRequest
> = z.object({
  id: z.string(),
  body: z.optional(models.DtoDeleteCreditGrantRequest$outboundSchema),
});

export function deleteCreditGrantRequestToJSON(
  deleteCreditGrantRequest: DeleteCreditGrantRequest,
): string {
  return JSON.stringify(
    DeleteCreditGrantRequest$outboundSchema.parse(deleteCreditGrantRequest),
  );
}
