/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type DeletePriceRequest = {
  /**
   * Price ID
   */
  id: string;
  /**
   * Delete Price Request
   */
  body: models.DtoDeletePriceRequest;
};

/** @internal */
export type DeletePriceRequest$Outbound = {
  id: string;
  body: models.DtoDeletePriceRequest$Outbound;
};

/** @internal */
export const DeletePriceRequest$outboundSchema: z.ZodMiniType<
  DeletePriceRequest$Outbound,
  DeletePriceRequest
> = z.object({
  id: z.string(),
  body: models.DtoDeletePriceRequest$outboundSchema,
});

export function deletePriceRequestToJSON(
  deletePriceRequest: DeletePriceRequest,
): string {
  return JSON.stringify(
    DeletePriceRequest$outboundSchema.parse(deletePriceRequest),
  );
}
