/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetTenantRequest = {
  /**
   * Tenant ID
   */
  id: string;
};

/** @internal */
export type GetTenantRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetTenantRequest$outboundSchema: z.ZodMiniType<
  GetTenantRequest$Outbound,
  GetTenantRequest
> = z.object({
  id: z.string(),
});

export function getTenantRequestToJSON(
  getTenantRequest: GetTenantRequest,
): string {
  return JSON.stringify(
    GetTenantRequest$outboundSchema.parse(getTenantRequest),
  );
}
