/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PauseSubscriptionRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Pause subscription request
   */
  body: models.DtoPauseSubscriptionRequest;
};

/** @internal */
export type PauseSubscriptionRequest$Outbound = {
  id: string;
  body: models.DtoPauseSubscriptionRequest$Outbound;
};

/** @internal */
export const PauseSubscriptionRequest$outboundSchema: z.ZodMiniType<
  PauseSubscriptionRequest$Outbound,
  PauseSubscriptionRequest
> = z.object({
  id: z.string(),
  body: models.DtoPauseSubscriptionRequest$outboundSchema,
});

export function pauseSubscriptionRequestToJSON(
  pauseSubscriptionRequest: PauseSubscriptionRequest,
): string {
  return JSON.stringify(
    PauseSubscriptionRequest$outboundSchema.parse(pauseSubscriptionRequest),
  );
}
