/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PostPlansIdCloneRequest = {
  /**
   * Source Plan ID
   */
  id: string;
  /**
   * Clone configuration
   */
  body: models.DtoClonePlanRequest;
};

/** @internal */
export type PostPlansIdCloneRequest$Outbound = {
  id: string;
  body: models.DtoClonePlanRequest$Outbound;
};

/** @internal */
export const PostPlansIdCloneRequest$outboundSchema: z.ZodMiniType<
  PostPlansIdCloneRequest$Outbound,
  PostPlansIdCloneRequest
> = z.object({
  id: z.string(),
  body: models.DtoClonePlanRequest$outboundSchema,
});

export function postPlansIdCloneRequestToJSON(
  postPlansIdCloneRequest: PostPlansIdCloneRequest,
): string {
  return JSON.stringify(
    PostPlansIdCloneRequest$outboundSchema.parse(postPlansIdCloneRequest),
  );
}
