/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type ResumeSubscriptionRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Resume subscription request
   */
  body: models.DtoResumeSubscriptionRequest;
};

/** @internal */
export type ResumeSubscriptionRequest$Outbound = {
  id: string;
  body: models.DtoResumeSubscriptionRequest$Outbound;
};

/** @internal */
export const ResumeSubscriptionRequest$outboundSchema: z.ZodMiniType<
  ResumeSubscriptionRequest$Outbound,
  ResumeSubscriptionRequest
> = z.object({
  id: z.string(),
  body: models.DtoResumeSubscriptionRequest$outboundSchema,
});

export function resumeSubscriptionRequestToJSON(
  resumeSubscriptionRequest: ResumeSubscriptionRequest,
): string {
  return JSON.stringify(
    ResumeSubscriptionRequest$outboundSchema.parse(resumeSubscriptionRequest),
  );
}
