/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type TopUpWalletRequest = {
  /**
   * Wallet ID
   */
  id: string;
  /**
   * Top up request
   */
  body: models.DtoTopUpWalletRequest;
};

/** @internal */
export type TopUpWalletRequest$Outbound = {
  id: string;
  body: models.DtoTopUpWalletRequest$Outbound;
};

/** @internal */
export const TopUpWalletRequest$outboundSchema: z.ZodMiniType<
  TopUpWalletRequest$Outbound,
  TopUpWalletRequest
> = z.object({
  id: z.string(),
  body: models.DtoTopUpWalletRequest$outboundSchema,
});

export function topUpWalletRequestToJSON(
  topUpWalletRequest: TopUpWalletRequest,
): string {
  return JSON.stringify(
    TopUpWalletRequest$outboundSchema.parse(topUpWalletRequest),
  );
}
