/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateWalletRequest = {
  /**
   * Wallet ID
   */
  id: string;
  /**
   * Update wallet request
   */
  body: models.DtoUpdateWalletRequest;
};

/** @internal */
export type UpdateWalletRequest$Outbound = {
  id: string;
  body: models.DtoUpdateWalletRequest$Outbound;
};

/** @internal */
export const UpdateWalletRequest$outboundSchema: z.ZodMiniType<
  UpdateWalletRequest$Outbound,
  UpdateWalletRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdateWalletRequest$outboundSchema,
});

export function updateWalletRequestToJSON(
  updateWalletRequest: UpdateWalletRequest,
): string {
  return JSON.stringify(
    UpdateWalletRequest$outboundSchema.parse(updateWalletRequest),
  );
}
