/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateInvoicePaymentStatusRequest = {
  /**
   * Invoice ID
   */
  id: string;
  /**
   * Payment Status Update Request
   */
  body: models.DtoUpdatePaymentStatusRequest;
};

/** @internal */
export type UpdateInvoicePaymentStatusRequest$Outbound = {
  id: string;
  body: models.DtoUpdatePaymentStatusRequest$Outbound;
};

/** @internal */
export const UpdateInvoicePaymentStatusRequest$outboundSchema: z.ZodMiniType<
  UpdateInvoicePaymentStatusRequest$Outbound,
  UpdateInvoicePaymentStatusRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdatePaymentStatusRequest$outboundSchema,
});

export function updateInvoicePaymentStatusRequestToJSON(
  updateInvoicePaymentStatusRequest: UpdateInvoicePaymentStatusRequest,
): string {
  return JSON.stringify(
    UpdateInvoicePaymentStatusRequest$outboundSchema.parse(
      updateInvoicePaymentStatusRequest,
    ),
  );
}
