/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateEntitlementRequest = {
  /**
   * Entitlement ID
   */
  id: string;
  /**
   * Entitlement configuration
   */
  body: models.DtoUpdateEntitlementRequest;
};

/** @internal */
export type UpdateEntitlementRequest$Outbound = {
  id: string;
  body: models.DtoUpdateEntitlementRequest$Outbound;
};

/** @internal */
export const UpdateEntitlementRequest$outboundSchema: z.ZodMiniType<
  UpdateEntitlementRequest$Outbound,
  UpdateEntitlementRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdateEntitlementRequest$outboundSchema,
});

export function updateEntitlementRequestToJSON(
  updateEntitlementRequest: UpdateEntitlementRequest,
): string {
  return JSON.stringify(
    UpdateEntitlementRequest$outboundSchema.parse(updateEntitlementRequest),
  );
}
