/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateScheduledTaskRequest = {
  /**
   * Scheduled Task ID
   */
  id: string;
  /**
   * Update request (enabled: true/false to pause/resume)
   */
  body: models.DtoUpdateScheduledTaskRequest;
};

/** @internal */
export type UpdateScheduledTaskRequest$Outbound = {
  id: string;
  body: models.DtoUpdateScheduledTaskRequest$Outbound;
};

/** @internal */
export const UpdateScheduledTaskRequest$outboundSchema: z.ZodMiniType<
  UpdateScheduledTaskRequest$Outbound,
  UpdateScheduledTaskRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdateScheduledTaskRequest$outboundSchema,
});

export function updateScheduledTaskRequestToJSON(
  updateScheduledTaskRequest: UpdateScheduledTaskRequest,
): string {
  return JSON.stringify(
    UpdateScheduledTaskRequest$outboundSchema.parse(updateScheduledTaskRequest),
  );
}
