/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateCouponRequest = {
  /**
   * Coupon ID
   */
  id: string;
  /**
   * Coupon update request
   */
  body: models.DtoUpdateCouponRequest;
};

/** @internal */
export type UpdateCouponRequest$Outbound = {
  id: string;
  body: models.DtoUpdateCouponRequest$Outbound;
};

/** @internal */
export const UpdateCouponRequest$outboundSchema: z.ZodMiniType<
  UpdateCouponRequest$Outbound,
  UpdateCouponRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdateCouponRequest$outboundSchema,
});

export function updateCouponRequestToJSON(
  updateCouponRequest: UpdateCouponRequest,
): string {
  return JSON.stringify(
    UpdateCouponRequest$outboundSchema.parse(updateCouponRequest),
  );
}
