/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateCreditGrantRequest = {
  /**
   * Credit Grant ID
   */
  id: string;
  /**
   * Credit Grant configuration
   */
  body: models.DtoUpdateCreditGrantRequest;
};

/** @internal */
export type UpdateCreditGrantRequest$Outbound = {
  id: string;
  body: models.DtoUpdateCreditGrantRequest$Outbound;
};

/** @internal */
export const UpdateCreditGrantRequest$outboundSchema: z.ZodMiniType<
  UpdateCreditGrantRequest$Outbound,
  UpdateCreditGrantRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdateCreditGrantRequest$outboundSchema,
});

export function updateCreditGrantRequestToJSON(
  updateCreditGrantRequest: UpdateCreditGrantRequest,
): string {
  return JSON.stringify(
    UpdateCreditGrantRequest$outboundSchema.parse(updateCreditGrantRequest),
  );
}
