/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdatePlanRequest = {
  /**
   * Plan ID
   */
  id: string;
  /**
   * Plan update
   */
  body: models.DtoUpdatePlanRequest;
};

/** @internal */
export type UpdatePlanRequest$Outbound = {
  id: string;
  body: models.DtoUpdatePlanRequest$Outbound;
};

/** @internal */
export const UpdatePlanRequest$outboundSchema: z.ZodMiniType<
  UpdatePlanRequest$Outbound,
  UpdatePlanRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdatePlanRequest$outboundSchema,
});

export function updatePlanRequestToJSON(
  updatePlanRequest: UpdatePlanRequest,
): string {
  return JSON.stringify(
    UpdatePlanRequest$outboundSchema.parse(updatePlanRequest),
  );
}
