/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdatePaymentRequest = {
  /**
   * Payment ID
   */
  id: string;
  /**
   * Payment configuration
   */
  body: models.DtoUpdatePaymentRequest;
};

/** @internal */
export type UpdatePaymentRequest$Outbound = {
  id: string;
  body: models.DtoUpdatePaymentRequest$Outbound;
};

/** @internal */
export const UpdatePaymentRequest$outboundSchema: z.ZodMiniType<
  UpdatePaymentRequest$Outbound,
  UpdatePaymentRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdatePaymentRequest$outboundSchema,
});

export function updatePaymentRequestToJSON(
  updatePaymentRequest: UpdatePaymentRequest,
): string {
  return JSON.stringify(
    UpdatePaymentRequest$outboundSchema.parse(updatePaymentRequest),
  );
}
