/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateCostsheetRequest = {
  /**
   * Costsheet ID
   */
  id: string;
  /**
   * Costsheet configuration
   */
  body: models.DtoUpdateCostsheetRequest;
};

/** @internal */
export type UpdateCostsheetRequest$Outbound = {
  id: string;
  body: models.DtoUpdateCostsheetRequest$Outbound;
};

/** @internal */
export const UpdateCostsheetRequest$outboundSchema: z.ZodMiniType<
  UpdateCostsheetRequest$Outbound,
  UpdateCostsheetRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdateCostsheetRequest$outboundSchema,
});

export function updateCostsheetRequestToJSON(
  updateCostsheetRequest: UpdateCostsheetRequest,
): string {
  return JSON.stringify(
    UpdateCostsheetRequest$outboundSchema.parse(updateCostsheetRequest),
  );
}
