/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateTaxRateRequest = {
  /**
   * Tax rate ID
   */
  id: string;
  /**
   * Tax rate to update
   */
  body: models.DtoUpdateTaxRateRequest;
};

/** @internal */
export type UpdateTaxRateRequest$Outbound = {
  id: string;
  body: models.DtoUpdateTaxRateRequest$Outbound;
};

/** @internal */
export const UpdateTaxRateRequest$outboundSchema: z.ZodMiniType<
  UpdateTaxRateRequest$Outbound,
  UpdateTaxRateRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdateTaxRateRequest$outboundSchema,
});

export function updateTaxRateRequestToJSON(
  updateTaxRateRequest: UpdateTaxRateRequest,
): string {
  return JSON.stringify(
    UpdateTaxRateRequest$outboundSchema.parse(updateTaxRateRequest),
  );
}
