/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateSubscriptionRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Update Subscription Request
   */
  body: models.DtoUpdateSubscriptionRequest;
};

/** @internal */
export type UpdateSubscriptionRequest$Outbound = {
  id: string;
  body: models.DtoUpdateSubscriptionRequest$Outbound;
};

/** @internal */
export const UpdateSubscriptionRequest$outboundSchema: z.ZodMiniType<
  UpdateSubscriptionRequest$Outbound,
  UpdateSubscriptionRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdateSubscriptionRequest$outboundSchema,
});

export function updateSubscriptionRequestToJSON(
  updateSubscriptionRequest: UpdateSubscriptionRequest,
): string {
  return JSON.stringify(
    UpdateSubscriptionRequest$outboundSchema.parse(updateSubscriptionRequest),
  );
}
