/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateTaxAssociationRequest = {
  /**
   * Tax Config ID
   */
  id: string;
  /**
   * Tax Config Request
   */
  body: models.DtoTaxAssociationUpdateRequest;
};

/** @internal */
export type UpdateTaxAssociationRequest$Outbound = {
  id: string;
  body: models.DtoTaxAssociationUpdateRequest$Outbound;
};

/** @internal */
export const UpdateTaxAssociationRequest$outboundSchema: z.ZodMiniType<
  UpdateTaxAssociationRequest$Outbound,
  UpdateTaxAssociationRequest
> = z.object({
  id: z.string(),
  body: models.DtoTaxAssociationUpdateRequest$outboundSchema,
});

export function updateTaxAssociationRequestToJSON(
  updateTaxAssociationRequest: UpdateTaxAssociationRequest,
): string {
  return JSON.stringify(
    UpdateTaxAssociationRequest$outboundSchema.parse(
      updateTaxAssociationRequest,
    ),
  );
}
