/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateFeatureRequest = {
  /**
   * Feature ID
   */
  id: string;
  /**
   * Feature update data
   */
  body: models.DtoUpdateFeatureRequest;
};

/** @internal */
export type UpdateFeatureRequest$Outbound = {
  id: string;
  body: models.DtoUpdateFeatureRequest$Outbound;
};

/** @internal */
export const UpdateFeatureRequest$outboundSchema: z.ZodMiniType<
  UpdateFeatureRequest$Outbound,
  UpdateFeatureRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdateFeatureRequest$outboundSchema,
});

export function updateFeatureRequestToJSON(
  updateFeatureRequest: UpdateFeatureRequest,
): string {
  return JSON.stringify(
    UpdateFeatureRequest$outboundSchema.parse(updateFeatureRequest),
  );
}
