/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateTaskStatusRequest = {
  /**
   * Task ID
   */
  id: string;
  /**
   * Status update
   */
  body: models.DtoUpdateTaskStatusRequest;
};

/** @internal */
export type UpdateTaskStatusRequest$Outbound = {
  id: string;
  body: models.DtoUpdateTaskStatusRequest$Outbound;
};

/** @internal */
export const UpdateTaskStatusRequest$outboundSchema: z.ZodMiniType<
  UpdateTaskStatusRequest$Outbound,
  UpdateTaskStatusRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdateTaskStatusRequest$outboundSchema,
});

export function updateTaskStatusRequestToJSON(
  updateTaskStatusRequest: UpdateTaskStatusRequest,
): string {
  return JSON.stringify(
    UpdateTaskStatusRequest$outboundSchema.parse(updateTaskStatusRequest),
  );
}
