/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateAddonRequest = {
  /**
   * Addon ID
   */
  id: string;
  /**
   * Update Addon Request
   */
  body: models.DtoUpdateAddonRequest;
};

/** @internal */
export type UpdateAddonRequest$Outbound = {
  id: string;
  body: models.DtoUpdateAddonRequest$Outbound;
};

/** @internal */
export const UpdateAddonRequest$outboundSchema: z.ZodMiniType<
  UpdateAddonRequest$Outbound,
  UpdateAddonRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdateAddonRequest$outboundSchema,
});

export function updateAddonRequestToJSON(
  updateAddonRequest: UpdateAddonRequest,
): string {
  return JSON.stringify(
    UpdateAddonRequest$outboundSchema.parse(updateAddonRequest),
  );
}
