/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdatePriceRequest = {
  /**
   * Price ID
   */
  id: string;
  /**
   * Price configuration
   */
  body: models.DtoUpdatePriceRequest;
};

/** @internal */
export type UpdatePriceRequest$Outbound = {
  id: string;
  body: models.DtoUpdatePriceRequest$Outbound;
};

/** @internal */
export const UpdatePriceRequest$outboundSchema: z.ZodMiniType<
  UpdatePriceRequest$Outbound,
  UpdatePriceRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdatePriceRequest$outboundSchema,
});

export function updatePriceRequestToJSON(
  updatePriceRequest: UpdatePriceRequest,
): string {
  return JSON.stringify(
    UpdatePriceRequest$outboundSchema.parse(updatePriceRequest),
  );
}
