/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  TypesCancelImmediatelyInvoicePolicy,
  TypesCancelImmediatelyInvoicePolicy$outboundSchema,
} from "./types-cancel-immediately-invoice-policy.js";
import {
  TypesCancellationType,
  TypesCancellationType$outboundSchema,
} from "./types-cancellation-type.js";
import {
  TypesProrationBehavior,
  TypesProrationBehavior$outboundSchema,
} from "./types-proration-behavior.js";

export type DtoCancelSubscriptionRequest = {
  cancelImmediatelyInovicePolicy?:
    | TypesCancelImmediatelyInvoicePolicy
    | undefined;
  cancellationType: TypesCancellationType;
  prorationBehavior?: TypesProrationBehavior | undefined;
  /**
   * Reason for cancellation (for audit and business intelligence)
   */
  reason?: string | undefined;
};

/** @internal */
export type DtoCancelSubscriptionRequest$Outbound = {
  cancel_immediately_inovice_policy?: string | undefined;
  cancellation_type: string;
  proration_behavior?: string | undefined;
  reason?: string | undefined;
};

/** @internal */
export const DtoCancelSubscriptionRequest$outboundSchema: z.ZodMiniType<
  DtoCancelSubscriptionRequest$Outbound,
  DtoCancelSubscriptionRequest
> = z.pipe(
  z.object({
    cancelImmediatelyInovicePolicy: z.optional(
      TypesCancelImmediatelyInvoicePolicy$outboundSchema,
    ),
    cancellationType: TypesCancellationType$outboundSchema,
    prorationBehavior: z.optional(TypesProrationBehavior$outboundSchema),
    reason: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      cancelImmediatelyInovicePolicy: "cancel_immediately_inovice_policy",
      cancellationType: "cancellation_type",
      prorationBehavior: "proration_behavior",
    });
  }),
);

export function dtoCancelSubscriptionRequestToJSON(
  dtoCancelSubscriptionRequest: DtoCancelSubscriptionRequest,
): string {
  return JSON.stringify(
    DtoCancelSubscriptionRequest$outboundSchema.parse(
      dtoCancelSubscriptionRequest,
    ),
  );
}
