/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DtoUserResponse,
  DtoUserResponse$inboundSchema,
} from "./dto-user-response.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$inboundSchema,
} from "./types-pagination-response.js";

export type DtoListUsersResponse = {
  items?: Array<DtoUserResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

/** @internal */
export const DtoListUsersResponse$inboundSchema: z.ZodMiniType<
  DtoListUsersResponse,
  unknown
> = z.object({
  items: types.optional(z.array(DtoUserResponse$inboundSchema)),
  pagination: types.optional(TypesPaginationResponse$inboundSchema),
});

export function dtoListUsersResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListUsersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListUsersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListUsersResponse' from JSON`,
  );
}
