/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DtoSubscriptionResponse,
  DtoSubscriptionResponse$inboundSchema,
} from "./dto-subscription-response.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$inboundSchema,
} from "./types-pagination-response.js";

export type DtoListSubscriptionsResponse = {
  items?: Array<DtoSubscriptionResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

/** @internal */
export const DtoListSubscriptionsResponse$inboundSchema: z.ZodMiniType<
  DtoListSubscriptionsResponse,
  unknown
> = z.object({
  items: types.optional(z.array(DtoSubscriptionResponse$inboundSchema)),
  pagination: types.optional(TypesPaginationResponse$inboundSchema),
});

export function dtoListSubscriptionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListSubscriptionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListSubscriptionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListSubscriptionsResponse' from JSON`,
  );
}
