/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$inboundSchema,
} from "./dto-customer-response.js";
import {
  DtoUserResponse,
  DtoUserResponse$inboundSchema,
} from "./dto-user-response.js";
import {
  DtoWalletResponse,
  DtoWalletResponse$inboundSchema,
} from "./dto-wallet-response.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { TypesStatus, TypesStatus$inboundSchema } from "./types-status.js";
import {
  TypesTransactionReason,
  TypesTransactionReason$inboundSchema,
} from "./types-transaction-reason.js";
import {
  TypesTransactionStatus,
  TypesTransactionStatus$inboundSchema,
} from "./types-transaction-status.js";
import {
  TypesTransactionType,
  TypesTransactionType$inboundSchema,
} from "./types-transaction-type.js";
import {
  TypesWalletTxReferenceType,
  TypesWalletTxReferenceType$inboundSchema,
} from "./types-wallet-tx-reference-type.js";

export type DtoWalletTransactionResponse = {
  amount?: string | undefined;
  /**
   * conversion_rate is the conversion rate for the transaction to the currency
   */
  conversionRate?: string | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  createdByUser?: DtoUserResponse | undefined;
  creditAmount?: string | undefined;
  creditBalanceAfter?: string | undefined;
  creditBalanceBefore?: string | undefined;
  creditsAvailable?: string | undefined;
  currency?: string | undefined;
  /**
   * Customer response object containing all customer information
   */
  customer?: DtoCustomerResponse | undefined;
  customerId?: string | undefined;
  description?: string | undefined;
  environmentId?: string | undefined;
  expiryDate?: string | undefined;
  id?: string | undefined;
  idempotencyKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  priority?: number | undefined;
  referenceId?: string | undefined;
  referenceType?: TypesWalletTxReferenceType | undefined;
  status?: TypesStatus | undefined;
  tenantId?: string | undefined;
  /**
   * topup_conversion_rate is the conversion rate for the topup to the currency
   */
  topupConversionRate?: string | undefined;
  transactionReason?: TypesTransactionReason | undefined;
  transactionStatus?: TypesTransactionStatus | undefined;
  type?: TypesTransactionType | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
  wallet?: DtoWalletResponse | undefined;
  walletId?: string | undefined;
};

/** @internal */
export const DtoWalletTransactionResponse$inboundSchema: z.ZodMiniType<
  DtoWalletTransactionResponse,
  unknown
> = z.pipe(
  z.object({
    amount: types.optional(types.string()),
    conversion_rate: types.optional(types.string()),
    created_at: types.optional(types.string()),
    created_by: types.optional(types.string()),
    created_by_user: types.optional(DtoUserResponse$inboundSchema),
    credit_amount: types.optional(types.string()),
    credit_balance_after: types.optional(types.string()),
    credit_balance_before: types.optional(types.string()),
    credits_available: types.optional(types.string()),
    currency: types.optional(types.string()),
    customer: types.optional(DtoCustomerResponse$inboundSchema),
    customer_id: types.optional(types.string()),
    description: types.optional(types.string()),
    environment_id: types.optional(types.string()),
    expiry_date: types.optional(types.string()),
    id: types.optional(types.string()),
    idempotency_key: types.optional(types.string()),
    metadata: types.optional(z.record(z.string(), types.string())),
    priority: types.optional(types.number()),
    reference_id: types.optional(types.string()),
    reference_type: types.optional(TypesWalletTxReferenceType$inboundSchema),
    status: types.optional(TypesStatus$inboundSchema),
    tenant_id: types.optional(types.string()),
    topup_conversion_rate: types.optional(types.string()),
    transaction_reason: types.optional(TypesTransactionReason$inboundSchema),
    transaction_status: types.optional(TypesTransactionStatus$inboundSchema),
    type: types.optional(TypesTransactionType$inboundSchema),
    updated_at: types.optional(types.string()),
    updated_by: types.optional(types.string()),
    wallet: types.optional(DtoWalletResponse$inboundSchema),
    wallet_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "conversion_rate": "conversionRate",
      "created_at": "createdAt",
      "created_by": "createdBy",
      "created_by_user": "createdByUser",
      "credit_amount": "creditAmount",
      "credit_balance_after": "creditBalanceAfter",
      "credit_balance_before": "creditBalanceBefore",
      "credits_available": "creditsAvailable",
      "customer_id": "customerId",
      "environment_id": "environmentId",
      "expiry_date": "expiryDate",
      "idempotency_key": "idempotencyKey",
      "reference_id": "referenceId",
      "reference_type": "referenceType",
      "tenant_id": "tenantId",
      "topup_conversion_rate": "topupConversionRate",
      "transaction_reason": "transactionReason",
      "transaction_status": "transactionStatus",
      "updated_at": "updatedAt",
      "updated_by": "updatedBy",
      "wallet_id": "walletId",
    });
  }),
);

export function dtoWalletTransactionResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoWalletTransactionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoWalletTransactionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoWalletTransactionResponse' from JSON`,
  );
}
