/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DtoTaxAssociationResponse,
  DtoTaxAssociationResponse$inboundSchema,
} from "./dto-tax-association-response.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$inboundSchema,
} from "./types-pagination-response.js";

export type DtoListTaxAssociationsResponse = {
  items?: Array<DtoTaxAssociationResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

/** @internal */
export const DtoListTaxAssociationsResponse$inboundSchema: z.ZodMiniType<
  DtoListTaxAssociationsResponse,
  unknown
> = z.object({
  items: types.optional(z.array(DtoTaxAssociationResponse$inboundSchema)),
  pagination: types.optional(TypesPaginationResponse$inboundSchema),
});

export function dtoListTaxAssociationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListTaxAssociationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListTaxAssociationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListTaxAssociationsResponse' from JSON`,
  );
}
