/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DtoDebugTracker,
  DtoDebugTracker$inboundSchema,
} from "./dto-debug-tracker.js";
import { DtoEvent, DtoEvent$inboundSchema } from "./dto-event.js";
import {
  DtoFeatureUsageInfo,
  DtoFeatureUsageInfo$inboundSchema,
} from "./dto-feature-usage-info.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TypesEventProcessingStatusType,
  TypesEventProcessingStatusType$inboundSchema,
} from "./types-event-processing-status-type.js";

export type DtoGetEventByIDResponse = {
  debugTracker?: DtoDebugTracker | undefined;
  event?: DtoEvent | undefined;
  processedEvents?: Array<DtoFeatureUsageInfo> | undefined;
  status?: TypesEventProcessingStatusType | undefined;
};

/** @internal */
export const DtoGetEventByIDResponse$inboundSchema: z.ZodMiniType<
  DtoGetEventByIDResponse,
  unknown
> = z.pipe(
  z.object({
    debug_tracker: types.optional(DtoDebugTracker$inboundSchema),
    event: types.optional(DtoEvent$inboundSchema),
    processed_events: types.optional(
      z.array(DtoFeatureUsageInfo$inboundSchema),
    ),
    status: types.optional(TypesEventProcessingStatusType$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "debug_tracker": "debugTracker",
      "processed_events": "processedEvents",
    });
  }),
);

export function dtoGetEventByIDResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoGetEventByIDResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoGetEventByIDResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoGetEventByIDResponse' from JSON`,
  );
}
