/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TypesScheduleStatus,
  TypesScheduleStatus$inboundSchema,
} from "./types-schedule-status.js";

/**
 * Confirmation of schedule cancellation
 */
export type DtoCancelScheduleResponse = {
  /**
   * message is a confirmation message
   */
  message?: string | undefined;
  status?: TypesScheduleStatus | undefined;
};

/** @internal */
export const DtoCancelScheduleResponse$inboundSchema: z.ZodMiniType<
  DtoCancelScheduleResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(TypesScheduleStatus$inboundSchema),
});

export function dtoCancelScheduleResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoCancelScheduleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoCancelScheduleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoCancelScheduleResponse' from JSON`,
  );
}
