/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  TypesAlertSettings,
  TypesAlertSettings$Outbound,
  TypesAlertSettings$outboundSchema,
} from "./types-alert-settings.js";
import {
  TypesAutoTopup,
  TypesAutoTopup$Outbound,
  TypesAutoTopup$outboundSchema,
} from "./types-auto-topup.js";
import {
  TypesWalletConfig,
  TypesWalletConfig$Outbound,
  TypesWalletConfig$outboundSchema,
} from "./types-wallet-config.js";

export type DtoUpdateWalletRequest = {
  alertSettings?: TypesAlertSettings | undefined;
  autoTopup?: TypesAutoTopup | undefined;
  config?: TypesWalletConfig | undefined;
  description?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

/** @internal */
export type DtoUpdateWalletRequest$Outbound = {
  alert_settings?: TypesAlertSettings$Outbound | undefined;
  auto_topup?: TypesAutoTopup$Outbound | undefined;
  config?: TypesWalletConfig$Outbound | undefined;
  description?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

/** @internal */
export const DtoUpdateWalletRequest$outboundSchema: z.ZodMiniType<
  DtoUpdateWalletRequest$Outbound,
  DtoUpdateWalletRequest
> = z.pipe(
  z.object({
    alertSettings: z.optional(TypesAlertSettings$outboundSchema),
    autoTopup: z.optional(TypesAutoTopup$outboundSchema),
    config: z.optional(TypesWalletConfig$outboundSchema),
    description: z.optional(z.string()),
    metadata: z.optional(z.record(z.string(), z.string())),
    name: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      alertSettings: "alert_settings",
      autoTopup: "auto_topup",
    });
  }),
);

export function dtoUpdateWalletRequestToJSON(
  dtoUpdateWalletRequest: DtoUpdateWalletRequest,
): string {
  return JSON.stringify(
    DtoUpdateWalletRequest$outboundSchema.parse(dtoUpdateWalletRequest),
  );
}
