/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DtoAlertLogResponse,
  DtoAlertLogResponse$inboundSchema,
} from "./dto-alert-log-response.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$inboundSchema,
} from "./types-pagination-response.js";

export type DtoListAlertLogsResponse = {
  items?: Array<DtoAlertLogResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

/** @internal */
export const DtoListAlertLogsResponse$inboundSchema: z.ZodMiniType<
  DtoListAlertLogsResponse,
  unknown
> = z.object({
  items: types.optional(z.array(DtoAlertLogResponse$inboundSchema)),
  pagination: types.optional(TypesPaginationResponse$inboundSchema),
});

export function dtoListAlertLogsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListAlertLogsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListAlertLogsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListAlertLogsResponse' from JSON`,
  );
}
