/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DtoGroupResponse,
  DtoGroupResponse$inboundSchema,
} from "./dto-group-response.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$inboundSchema,
} from "./types-pagination-response.js";

export type DtoListGroupsResponse = {
  items?: Array<DtoGroupResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

/** @internal */
export const DtoListGroupsResponse$inboundSchema: z.ZodMiniType<
  DtoListGroupsResponse,
  unknown
> = z.object({
  items: types.optional(z.array(DtoGroupResponse$inboundSchema)),
  pagination: types.optional(TypesPaginationResponse$inboundSchema),
});

export function dtoListGroupsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListGroupsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListGroupsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListGroupsResponse' from JSON`,
  );
}
