/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  TypesSubscriptionStatus,
  TypesSubscriptionStatus$outboundSchema,
} from "./types-subscription-status.js";

export type DtoUpdateSubscriptionRequest = {
  cancelAt?: string | undefined;
  cancelAtPeriodEnd?: boolean | undefined;
  /**
   * ParentSubscriptionID sets or clears the parent subscription. Omit to leave unchanged; send "" to clear.
   */
  parentSubscriptionId?: string | undefined;
  status?: TypesSubscriptionStatus | undefined;
};

/** @internal */
export type DtoUpdateSubscriptionRequest$Outbound = {
  cancel_at?: string | undefined;
  cancel_at_period_end?: boolean | undefined;
  parent_subscription_id?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const DtoUpdateSubscriptionRequest$outboundSchema: z.ZodMiniType<
  DtoUpdateSubscriptionRequest$Outbound,
  DtoUpdateSubscriptionRequest
> = z.pipe(
  z.object({
    cancelAt: z.optional(z.string()),
    cancelAtPeriodEnd: z.optional(z.boolean()),
    parentSubscriptionId: z.optional(z.string()),
    status: z.optional(TypesSubscriptionStatus$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      cancelAt: "cancel_at",
      cancelAtPeriodEnd: "cancel_at_period_end",
      parentSubscriptionId: "parent_subscription_id",
    });
  }),
);

export function dtoUpdateSubscriptionRequestToJSON(
  dtoUpdateSubscriptionRequest: DtoUpdateSubscriptionRequest,
): string {
  return JSON.stringify(
    DtoUpdateSubscriptionRequest$outboundSchema.parse(
      dtoUpdateSubscriptionRequest,
    ),
  );
}
