/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TypesEventProcessingStatusType = {
  Processed: "processed",
  Processing: "processing",
  Failed: "failed",
} as const;
export type TypesEventProcessingStatusType = OpenEnum<
  typeof TypesEventProcessingStatusType
>;

/** @internal */
export const TypesEventProcessingStatusType$inboundSchema: z.ZodMiniType<
  TypesEventProcessingStatusType,
  unknown
> = openEnums.inboundSchema(TypesEventProcessingStatusType);
