/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TypesPaymentTerms = {
  FifteenNET: "15 NET",
  ThirtyNET: "30 NET",
  FortyFiveNET: "45 NET",
  SixtyNET: "60 NET",
  SeventyFiveNET: "75 NET",
  NinetyNET: "90 NET",
} as const;
export type TypesPaymentTerms = OpenEnum<typeof TypesPaymentTerms>;

/** @internal */
export const TypesPaymentTerms$inboundSchema: z.ZodMiniType<
  TypesPaymentTerms,
  unknown
> = openEnums.inboundSchema(TypesPaymentTerms);
/** @internal */
export const TypesPaymentTerms$outboundSchema: z.ZodMiniType<
  string,
  TypesPaymentTerms
> = openEnums.outboundSchema(TypesPaymentTerms);
