/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errors-error-response.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TypesFailurePointType,
  TypesFailurePointType$inboundSchema,
} from "./types-failure-point-type.js";

export type TypesFailurePoint = {
  error?: ErrorsErrorResponse | undefined;
  failurePointType?: TypesFailurePointType | undefined;
};

/** @internal */
export const TypesFailurePoint$inboundSchema: z.ZodMiniType<
  TypesFailurePoint,
  unknown
> = z.pipe(
  z.object({
    error: types.optional(ErrorsErrorResponse$inboundSchema),
    failure_point_type: types.optional(TypesFailurePointType$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "failure_point_type": "failurePointType",
    });
  }),
);

export function typesFailurePointFromJSON(
  jsonString: string,
): SafeParseResult<TypesFailurePoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypesFailurePoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypesFailurePoint' from JSON`,
  );
}
