/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TypesCreditBreakdown = {
  free?: string | undefined;
  purchased?: string | undefined;
};

/** @internal */
export const TypesCreditBreakdown$inboundSchema: z.ZodMiniType<
  TypesCreditBreakdown,
  unknown
> = z.object({
  free: types.optional(types.string()),
  purchased: types.optional(types.string()),
});

export function typesCreditBreakdownFromJSON(
  jsonString: string,
): SafeParseResult<TypesCreditBreakdown, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypesCreditBreakdown$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypesCreditBreakdown' from JSON`,
  );
}
