/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TypesDebugTrackerStatus = {
  Unprocessed: "unprocessed",
  NotFound: "not_found",
  Found: "found",
  Error: "error",
} as const;
export type TypesDebugTrackerStatus = OpenEnum<typeof TypesDebugTrackerStatus>;

/** @internal */
export const TypesDebugTrackerStatus$inboundSchema: z.ZodMiniType<
  TypesDebugTrackerStatus,
  unknown
> = openEnums.inboundSchema(TypesDebugTrackerStatus);
