/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$Outbound,
  TypesFilterCondition$outboundSchema,
} from "./types-filter-condition.js";
import {
  TypesSortCondition,
  TypesSortCondition$Outbound,
  TypesSortCondition$outboundSchema,
} from "./types-sort-condition.js";
import { TypesStatus, TypesStatus$outboundSchema } from "./types-status.js";

export const TypesWorkflowExecutionFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesWorkflowExecutionFilterOrder = ClosedEnum<
  typeof TypesWorkflowExecutionFilterOrder
>;

export type TypesWorkflowExecutionFilter = {
  endTime?: string | undefined;
  /**
   * e.g. plan, invoice, subscription
   */
  entity?: string | undefined;
  /**
   * e.g. plan_01ABC123
   */
  entityId?: string | undefined;
  expand?: string | undefined;
  /**
   * filters allows complex filtering based on multiple fields (same as FeatureFilter)
   */
  filters?: Array<TypesFilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesWorkflowExecutionFilterOrder | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  startTime?: string | undefined;
  status?: TypesStatus | undefined;
  taskQueue?: string | undefined;
  /**
   * Workflow-specific filters
   */
  workflowId?: string | undefined;
  /**
   * e.g. Running, Completed, Failed
   */
  workflowStatus?: string | undefined;
  workflowType?: string | undefined;
};

/** @internal */
export const TypesWorkflowExecutionFilterOrder$outboundSchema: z.ZodMiniEnum<
  typeof TypesWorkflowExecutionFilterOrder
> = z.enum(TypesWorkflowExecutionFilterOrder);

/** @internal */
export type TypesWorkflowExecutionFilter$Outbound = {
  end_time?: string | undefined;
  entity?: string | undefined;
  entity_id?: string | undefined;
  expand?: string | undefined;
  filters?: Array<TypesFilterCondition$Outbound> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  sort?: Array<TypesSortCondition$Outbound> | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
  task_queue?: string | undefined;
  workflow_id?: string | undefined;
  workflow_status?: string | undefined;
  workflow_type?: string | undefined;
};

/** @internal */
export const TypesWorkflowExecutionFilter$outboundSchema: z.ZodMiniType<
  TypesWorkflowExecutionFilter$Outbound,
  TypesWorkflowExecutionFilter
> = z.pipe(
  z.object({
    endTime: z.optional(z.string()),
    entity: z.optional(z.string()),
    entityId: z.optional(z.string()),
    expand: z.optional(z.string()),
    filters: z.optional(z.array(TypesFilterCondition$outboundSchema)),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    order: z.optional(TypesWorkflowExecutionFilterOrder$outboundSchema),
    sort: z.optional(z.array(TypesSortCondition$outboundSchema)),
    startTime: z.optional(z.string()),
    status: z.optional(TypesStatus$outboundSchema),
    taskQueue: z.optional(z.string()),
    workflowId: z.optional(z.string()),
    workflowStatus: z.optional(z.string()),
    workflowType: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      endTime: "end_time",
      entityId: "entity_id",
      startTime: "start_time",
      taskQueue: "task_queue",
      workflowId: "workflow_id",
      workflowStatus: "workflow_status",
      workflowType: "workflow_type",
    });
  }),
);

export function typesWorkflowExecutionFilterToJSON(
  typesWorkflowExecutionFilter: TypesWorkflowExecutionFilter,
): string {
  return JSON.stringify(
    TypesWorkflowExecutionFilter$outboundSchema.parse(
      typesWorkflowExecutionFilter,
    ),
  );
}
