/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TypesWalletType = {
  PrePaid: "PRE_PAID",
  PostPaid: "POST_PAID",
} as const;
export type TypesWalletType = OpenEnum<typeof TypesWalletType>;

/** @internal */
export const TypesWalletType$inboundSchema: z.ZodMiniType<
  TypesWalletType,
  unknown
> = openEnums.inboundSchema(TypesWalletType);
/** @internal */
export const TypesWalletType$outboundSchema: z.ZodMiniType<
  string,
  TypesWalletType
> = openEnums.outboundSchema(TypesWalletType);
