/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TypesFailurePointType = {
  CustomerLookup: "customer_lookup",
  MeterLookup: "meter_lookup",
  PriceLookup: "price_lookup",
  SubscriptionLineItemLookup: "subscription_line_item_lookup",
} as const;
export type TypesFailurePointType = OpenEnum<typeof TypesFailurePointType>;

/** @internal */
export const TypesFailurePointType$inboundSchema: z.ZodMiniType<
  TypesFailurePointType,
  unknown
> = openEnums.inboundSchema(TypesFailurePointType);
