/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$Outbound,
  TypesFilterCondition$outboundSchema,
} from "./types-filter-condition.js";
import {
  TypesPriceEntityType,
  TypesPriceEntityType$outboundSchema,
} from "./types-price-entity-type.js";
import { TypesStatus, TypesStatus$outboundSchema } from "./types-status.js";

export const TypesPriceFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesPriceFilterOrder = ClosedEnum<typeof TypesPriceFilterOrder>;

export type TypesPriceFilter = {
  allowExpiredPrices?: boolean | undefined;
  endTime?: string | undefined;
  entityIds?: Array<string> | undefined;
  entityType?: TypesPriceEntityType | undefined;
  expand?: string | undefined;
  /**
   * DSL filters
   */
  filters?: Array<TypesFilterCondition> | undefined;
  limit?: number | undefined;
  meterIds?: Array<string> | undefined;
  offset?: number | undefined;
  order?: TypesPriceFilterOrder | undefined;
  parentPriceId?: string | undefined;
  /**
   * Price override filtering fields
   */
  planIds?: Array<string> | undefined;
  priceIds?: Array<string> | undefined;
  sort?: string | undefined;
  startDateLt?: string | undefined;
  startTime?: string | undefined;
  status?: TypesStatus | undefined;
  subscriptionId?: string | undefined;
};

/** @internal */
export const TypesPriceFilterOrder$outboundSchema: z.ZodMiniEnum<
  typeof TypesPriceFilterOrder
> = z.enum(TypesPriceFilterOrder);

/** @internal */
export type TypesPriceFilter$Outbound = {
  allow_expired_prices: boolean;
  end_time?: string | undefined;
  entity_ids?: Array<string> | undefined;
  entity_type?: string | undefined;
  expand?: string | undefined;
  filters?: Array<TypesFilterCondition$Outbound> | undefined;
  limit?: number | undefined;
  meter_ids?: Array<string> | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  parent_price_id?: string | undefined;
  plan_ids?: Array<string> | undefined;
  price_ids?: Array<string> | undefined;
  sort?: string | undefined;
  start_date_lt?: string | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
  subscription_id?: string | undefined;
};

/** @internal */
export const TypesPriceFilter$outboundSchema: z.ZodMiniType<
  TypesPriceFilter$Outbound,
  TypesPriceFilter
> = z.pipe(
  z.object({
    allowExpiredPrices: z._default(z.boolean(), false),
    endTime: z.optional(z.string()),
    entityIds: z.optional(z.array(z.string())),
    entityType: z.optional(TypesPriceEntityType$outboundSchema),
    expand: z.optional(z.string()),
    filters: z.optional(z.array(TypesFilterCondition$outboundSchema)),
    limit: z.optional(z.int()),
    meterIds: z.optional(z.array(z.string())),
    offset: z.optional(z.int()),
    order: z.optional(TypesPriceFilterOrder$outboundSchema),
    parentPriceId: z.optional(z.string()),
    planIds: z.optional(z.array(z.string())),
    priceIds: z.optional(z.array(z.string())),
    sort: z.optional(z.string()),
    startDateLt: z.optional(z.string()),
    startTime: z.optional(z.string()),
    status: z.optional(TypesStatus$outboundSchema),
    subscriptionId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      allowExpiredPrices: "allow_expired_prices",
      endTime: "end_time",
      entityIds: "entity_ids",
      entityType: "entity_type",
      meterIds: "meter_ids",
      parentPriceId: "parent_price_id",
      planIds: "plan_ids",
      priceIds: "price_ids",
      startDateLt: "start_date_lt",
      startTime: "start_time",
      subscriptionId: "subscription_id",
    });
  }),
);

export function typesPriceFilterToJSON(
  typesPriceFilter: TypesPriceFilter,
): string {
  return JSON.stringify(
    TypesPriceFilter$outboundSchema.parse(typesPriceFilter),
  );
}
