/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TypesAddonType = {
  Onetime: "onetime",
  MultipleInstance: "multiple_instance",
} as const;
export type TypesAddonType = OpenEnum<typeof TypesAddonType>;

/** @internal */
export const TypesAddonType$inboundSchema: z.ZodMiniType<
  TypesAddonType,
  unknown
> = openEnums.inboundSchema(TypesAddonType);
/** @internal */
export const TypesAddonType$outboundSchema: z.ZodMiniType<
  string,
  TypesAddonType
> = openEnums.outboundSchema(TypesAddonType);
