/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$Outbound,
  TypesFilterCondition$outboundSchema,
} from "./types-filter-condition.js";
import {
  TypesSortCondition,
  TypesSortCondition$Outbound,
  TypesSortCondition$outboundSchema,
} from "./types-sort-condition.js";
import { TypesStatus, TypesStatus$outboundSchema } from "./types-status.js";

export const TypesGroupFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesGroupFilterOrder = ClosedEnum<typeof TypesGroupFilterOrder>;

export type TypesGroupFilter = {
  endTime?: string | undefined;
  entityType?: string | undefined;
  expand?: string | undefined;
  /**
   * filters allows complex filtering based on multiple fields
   */
  filters?: Array<TypesFilterCondition> | undefined;
  /**
   * Group specific filters
   */
  groupIds?: Array<string> | undefined;
  limit?: number | undefined;
  lookupKey?: string | undefined;
  name?: string | undefined;
  offset?: number | undefined;
  order?: TypesGroupFilterOrder | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  startTime?: string | undefined;
  status?: TypesStatus | undefined;
};

/** @internal */
export const TypesGroupFilterOrder$outboundSchema: z.ZodMiniEnum<
  typeof TypesGroupFilterOrder
> = z.enum(TypesGroupFilterOrder);

/** @internal */
export type TypesGroupFilter$Outbound = {
  end_time?: string | undefined;
  entity_type?: string | undefined;
  expand?: string | undefined;
  filters?: Array<TypesFilterCondition$Outbound> | undefined;
  group_ids?: Array<string> | undefined;
  limit?: number | undefined;
  lookup_key?: string | undefined;
  name?: string | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  sort?: Array<TypesSortCondition$Outbound> | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const TypesGroupFilter$outboundSchema: z.ZodMiniType<
  TypesGroupFilter$Outbound,
  TypesGroupFilter
> = z.pipe(
  z.object({
    endTime: z.optional(z.string()),
    entityType: z.optional(z.string()),
    expand: z.optional(z.string()),
    filters: z.optional(z.array(TypesFilterCondition$outboundSchema)),
    groupIds: z.optional(z.array(z.string())),
    limit: z.optional(z.int()),
    lookupKey: z.optional(z.string()),
    name: z.optional(z.string()),
    offset: z.optional(z.int()),
    order: z.optional(TypesGroupFilterOrder$outboundSchema),
    sort: z.optional(z.array(TypesSortCondition$outboundSchema)),
    startTime: z.optional(z.string()),
    status: z.optional(TypesStatus$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      endTime: "end_time",
      entityType: "entity_type",
      groupIds: "group_ids",
      lookupKey: "lookup_key",
      startTime: "start_time",
    });
  }),
);

export function typesGroupFilterToJSON(
  typesGroupFilter: TypesGroupFilter,
): string {
  return JSON.stringify(
    TypesGroupFilter$outboundSchema.parse(typesGroupFilter),
  );
}
