/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$Outbound,
  TypesFilterCondition$outboundSchema,
} from "./types-filter-condition.js";
import {
  TypesSortCondition,
  TypesSortCondition$Outbound,
  TypesSortCondition$outboundSchema,
} from "./types-sort-condition.js";
import { TypesStatus, TypesStatus$outboundSchema } from "./types-status.js";

export const TypesCouponFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesCouponFilterOrder = ClosedEnum<typeof TypesCouponFilterOrder>;

export type TypesCouponFilter = {
  couponIds?: Array<string> | undefined;
  expand?: string | undefined;
  filters?: Array<TypesFilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesCouponFilterOrder | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  status?: TypesStatus | undefined;
};

/** @internal */
export const TypesCouponFilterOrder$outboundSchema: z.ZodMiniEnum<
  typeof TypesCouponFilterOrder
> = z.enum(TypesCouponFilterOrder);

/** @internal */
export type TypesCouponFilter$Outbound = {
  coupon_ids?: Array<string> | undefined;
  expand?: string | undefined;
  filters?: Array<TypesFilterCondition$Outbound> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  sort?: Array<TypesSortCondition$Outbound> | undefined;
  status?: string | undefined;
};

/** @internal */
export const TypesCouponFilter$outboundSchema: z.ZodMiniType<
  TypesCouponFilter$Outbound,
  TypesCouponFilter
> = z.pipe(
  z.object({
    couponIds: z.optional(z.array(z.string())),
    expand: z.optional(z.string()),
    filters: z.optional(z.array(TypesFilterCondition$outboundSchema)),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    order: z.optional(TypesCouponFilterOrder$outboundSchema),
    sort: z.optional(z.array(TypesSortCondition$outboundSchema)),
    status: z.optional(TypesStatus$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      couponIds: "coupon_ids",
    });
  }),
);

export function typesCouponFilterToJSON(
  typesCouponFilter: TypesCouponFilter,
): string {
  return JSON.stringify(
    TypesCouponFilter$outboundSchema.parse(typesCouponFilter),
  );
}
