/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$Outbound,
  TypesFilterCondition$outboundSchema,
} from "./types-filter-condition.js";
import {
  TypesSortCondition,
  TypesSortCondition$Outbound,
  TypesSortCondition$outboundSchema,
} from "./types-sort-condition.js";
import { TypesStatus, TypesStatus$outboundSchema } from "./types-status.js";

export const TypesPriceUnitFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesPriceUnitFilterOrder = ClosedEnum<
  typeof TypesPriceUnitFilterOrder
>;

export type TypesPriceUnitFilter = {
  endTime?: string | undefined;
  expand?: string | undefined;
  /**
   * filters allows complex filtering based on multiple fields
   */
  filters?: Array<TypesFilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesPriceUnitFilterOrder | undefined;
  priceUnitIds?: Array<string> | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  startTime?: string | undefined;
  status?: TypesStatus | undefined;
};

/** @internal */
export const TypesPriceUnitFilterOrder$outboundSchema: z.ZodMiniEnum<
  typeof TypesPriceUnitFilterOrder
> = z.enum(TypesPriceUnitFilterOrder);

/** @internal */
export type TypesPriceUnitFilter$Outbound = {
  end_time?: string | undefined;
  expand?: string | undefined;
  filters?: Array<TypesFilterCondition$Outbound> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  price_unit_ids?: Array<string> | undefined;
  sort?: Array<TypesSortCondition$Outbound> | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const TypesPriceUnitFilter$outboundSchema: z.ZodMiniType<
  TypesPriceUnitFilter$Outbound,
  TypesPriceUnitFilter
> = z.pipe(
  z.object({
    endTime: z.optional(z.string()),
    expand: z.optional(z.string()),
    filters: z.optional(z.array(TypesFilterCondition$outboundSchema)),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    order: z.optional(TypesPriceUnitFilterOrder$outboundSchema),
    priceUnitIds: z.optional(z.array(z.string())),
    sort: z.optional(z.array(TypesSortCondition$outboundSchema)),
    startTime: z.optional(z.string()),
    status: z.optional(TypesStatus$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      endTime: "end_time",
      priceUnitIds: "price_unit_ids",
      startTime: "start_time",
    });
  }),
);

export function typesPriceUnitFilterToJSON(
  typesPriceUnitFilter: TypesPriceUnitFilter,
): string {
  return JSON.stringify(
    TypesPriceUnitFilter$outboundSchema.parse(typesPriceUnitFilter),
  );
}
