/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TypesScheduleStatus = {
  Pending: "pending",
  Executing: "executing",
  Executed: "executed",
  Cancelled: "cancelled",
  Failed: "failed",
} as const;
export type TypesScheduleStatus = OpenEnum<typeof TypesScheduleStatus>;

/** @internal */
export const TypesScheduleStatus$inboundSchema: z.ZodMiniType<
  TypesScheduleStatus,
  unknown
> = openEnums.inboundSchema(TypesScheduleStatus);
