/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TypesSubscriptionScheduleChangeType = {
  PlanChange: "plan_change",
  Cancellation: "cancellation",
} as const;
export type TypesSubscriptionScheduleChangeType = OpenEnum<
  typeof TypesSubscriptionScheduleChangeType
>;

/** @internal */
export const TypesSubscriptionScheduleChangeType$inboundSchema: z.ZodMiniType<
  TypesSubscriptionScheduleChangeType,
  unknown
> = openEnums.inboundSchema(TypesSubscriptionScheduleChangeType);
/** @internal */
export const TypesSubscriptionScheduleChangeType$outboundSchema: z.ZodMiniType<
  string,
  TypesSubscriptionScheduleChangeType
> = openEnums.outboundSchema(TypesSubscriptionScheduleChangeType);
