/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const TypesScheduleType = {
  Immediate: "immediate",
  EndOfPeriod: "end_of_period",
} as const;
export type TypesScheduleType = ClosedEnum<typeof TypesScheduleType>;

/** @internal */
export const TypesScheduleType$outboundSchema: z.ZodMiniEnum<
  typeof TypesScheduleType
> = z.enum(TypesScheduleType);
